// <auto-generated />
using CMS.Models.Feeds;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CMS.Migrations
{
    [DbContext(typeof(FeedsContext))]
    [Migration("20190327140952_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CMS.Models.Feeds.Collection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("CMS.Models.Feeds.CollectionFeed", b =>
                {
                    b.Property<long>("CollectionId");

                    b.Property<long>("FeedId");

                    b.HasKey("CollectionId", "FeedId");

                    b.HasIndex("FeedId");

                    b.ToTable("CollectionFeed");
                });

            modelBuilder.Entity("CMS.Models.Feeds.Feed", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FeedType");

                    b.Property<string>("Url")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Feeds");
                });

            modelBuilder.Entity("CMS.Models.Feeds.NewsItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<long?>("FeedId");

                    b.Property<string>("Link");

                    b.Property<DateTime>("PublishDate");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("FeedId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("CMS.Models.Feeds.CollectionFeed", b =>
                {
                    b.HasOne("CMS.Models.Feeds.Collection", "Collection")
                        .WithMany("CollectionFeed")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CMS.Models.Feeds.Feed", "Feed")
                        .WithMany("CollectionFeed")
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CMS.Models.Feeds.NewsItem", b =>
                {
                    b.HasOne("CMS.Models.Feeds.Feed", "Feed")
                        .WithMany("News")
                        .HasForeignKey("FeedId");
                });
#pragma warning restore 612, 618
        }
    }
}
